import React from 'react'

export default function StanLee() {
    return (
        <div className='stan'>
            Excelsior! This became Stan Lee’s motto because it means ever upward or still higher. He created many Marvel superheros that we all know and love to this day. Some of them even made it to the big screen, with the most recent movie being the Avengers Endgame, which included a large amount of heroes in the MCU (Marvel Cinematic Universe). Stan Lee was born in New York City on December 28, 1922 and spent part of his life in the Great Depression. The important people in his life were his parents Jack and Celia Lieber and his younger brother. Stan Lee got a job in 1939 as an office assistant at Timely Comics. The most important places in his life were the Marvel Comic place and his home in New York. Stan Lee unfortunately died on November 12th, 2018. One of the important events in his life was when he helped co-create the Fantastic Four. Stan Lee was a revered comic-book creator who help make many superheroes we all know.
            <br/>
            <br/>

            Stan Lee had to help his family thrive through the Great Depression by doing whatever he could to make money. Eventually when the Great Depression passed, he then got a job as a comic book writer and co-created different characters. “Born in New York City on December 28, 1922, Stan Lee went on to work for the company that would eventually become Marvel Comics. With artist Jack Kirby, Lee launched the superhero team the Fantastic Four in 1961, and was soon responsible for creating popular characters like Spider-Man, the X-Men, the Hulk and Thor. Lee later worked in a number of comic-related business and multimedia ventures.” 
            <br/>
            <br/>
            Stan then continued on with his life and created relatable characters when he joined the company that is known as Marvel Comics today. Stan Lee was a proud high school graduate at the age of 16, and got a job as a comic writer and was promoted to editor in 1942. In the 1940s and ’50s during which time the group, later named Atlas, struggled financially, Lee created several comic-book series, including The Witness, The Destroyer, Jack Frost, Whizzer, and Black Marvel. “Lieber, who later shortened his name to "Lee" as a writer, went on to be hired as an office assistant at Timely Comics in 1939 and became an interim editor for the company in the early 1940s. Lee also served domestically in the Army during World War II, working as a writer and illustrator.” Stan Lee got a job in 1939 as an office assistant at Timely Comics. The name would soon change to the one of the most-known comic book companies on earth, Marvel Comics. Stan Lee helped create what Marvel is today. In 1961 Lee and Jack Kirby created The Fantastic Four, about four astronauts who gain superpowers after a cosmic incident. The series made them known as Marvel major forces in the comics world. Stan Lee changed the world of comics with help from multiple people. He helped make people smile with the material his team of comic book writers and illustrators created together.
            <br/>
            <br/>
            Stan also helped changed many people's lives drastically. A big example of that would be the actor Robert Downey Jr. Downey Jr. first appeared as Iron Man/Tony Stark a decade ago, helping to launch the actor back into major Hollywood roles. He went on to appear in a number of titles across the Marvel Universe, including two Iron Man sequels, the Avengers' movies, The Incredible Hulk, Captain America: Civil War and Spider-Man Homecoming. Stan Lee was a hero to many, and one of those many people he inspired was Robert Downey Jr., also known as Iron Man in the MCU (I love you 3000). Stan Lee helped Robert transition from a drug addict to a Hollywood star we all enjoy watching. Another one of those people is the famous actor Chris Evans,who played Captain America in the MCU. Chris and Stan both shared a strong, mutual respect for one another and would enjoy talking about there lives. When Stan Lee unfortunately passed away, Chris and many other actors tweeted out about the heartbreaking event. Chris said that there would never be another person like Stan Lee in a long time, and that he provided everyone with comfort and an escape.
            <br/>
            <br/>
            Stan did not only change lives with his words, he also affected many people with the comic books he would create. When jotting down ideas for the Fantastic Four, Lee conceived them as real, living people whose personal relationships would interest readers. Traditionally, comic books had very simple storylines. Fantastic Four, in contrast, honed in on the personalities of its heroes rather than solely focusing on their abilities. "'They were the kind of team I had been longing to write about,' Lee said. 'Heroes who were less than perfect.' Heroes who didn't always get along with each other, but heroes who could be counted on when the chips were down." Stan was loved by almost everyone who read the comics hie and his team created. It wasn't just because of the plot of the comic but also how the characters within the comic were more human than just something someone created just to create. With the characters being more humanlike, people were able to relate to the obstacles and problems that happened to different heroes in the many comics that were created. Not all the comics were able to connect with everyone the same way as other things, but his comics did create an escape for people.
            <br/>
            <br/>
            Everything Stan Lee has done was to make people happy, and he was successfully able to do that, with all the comic books, movies, TV shows, and everything else that he helped co-create. Unfortunately, Stan passed away at the age of 95 because of heart problems. The mark that he left on the world could never be shared with anyone. Stan did not only just make comics and make cameos in movies, he also would talk to people about how he got from being a boy in Brooklyn during the Great Depression to billionaire comic creator, and some those people he talked with became successful and lived a life most people dream of. Stan Lee was able to completely turn an actor's life around, as well as grow a small comic book company, and become the person people think of when talking about Marvel and how successful the company has been because of him. Stan Lee helped inspire me to not stop because of what of other people say, to always push forward and be kind to others and you will get far in life. He also inspired me to become an entrepreneur. The amount of success that came from Marvel helped Stan live an easy life to the point where if he wanted to do something he could do it. Without the famous comic book creator, the comic book world would be completely different than what it is now, and same goes for the movie world.
            <br/>
            <br/>
            *This essay was written by someone on google, not Blake Powelson. I just wanted to add another page to my website. Thank you whoever wrote this.*
        </div>
    )
}
